version: "3.2"

services:
  api:
    container_name: invoice_api
    build: ./api
    environment:
      PG_CONNECTION_STRING: postgres://example:example@store:5432/invoice_api_db

    ports:
      - 3000:3000
    volumes:
      - ./api/src:/usr/app/api/src


  db:
    container_name: store   
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: invoice_api_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432