version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: circleci/node:12.18
    steps:
       - checkout

       - run: cd api && npm ci
       - run: cd api && npm test
      
       - run: |
           cd api
           TAG="0.1.${CIRCLE_BUILD_NUM}"
           docker build -t seppeclottemans/invoice_api:$TAG .
           docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
           docker push seppeclottemans/invoice_api:$TAG